name: Chrome headless

on: push

jobs:
  chrome-headless:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Headless Chrome
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm start
          browser: chrome
